name: Package Manager

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"
      - run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
